version: '3.1'

services:
  postgres:
    image: postgres:11.5
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: cinema
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
  nginx:
    image: nginx:1.13
    ports:
      - 80:80
    volumes:
      - ./static:/usr/share/nginx/static
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

volumes:
  postgres:
